
FROM ubuntu:focal

ENV CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    DEBIAN_FRONTEND="noninteractive" \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8

# APT dependencies
RUN set -eux; \
    apt update -qy; \
    apt install -y \
        software-properties-common wget pkg-config git \
        rustc cargo \
        libpq-dev libsnappy-dev libsodium-dev software-properties-common \
        python3.8 python3.8-dev python3.8-venv python3.8-distutils \
        pipenv python3-dev python3-pip python3-wheel python3-requests python3-six python3-pytest; \
    mkdir -p $CARGO_HOME; \
    chmod -R a+w $CARGO_HOME; \
    rustc --version; \
    pipenv --version

# Compile and install diesel
RUN set -eux; \
    cargo install diesel_cli --version 1.3.1 --no-default-features --features postgres; \
    diesel --version

