# coding: utf-8

"""
    fatcat

    A scalable, versioned, API-oriented catalog of bibliographic entities and file metadata  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fatcat_client
from fatcat_client.models.stats_response import StatsResponse  # noqa: E501
from fatcat_client.rest import ApiException


class TestStatsResponse(unittest.TestCase):
    """StatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatsResponse(self):
        """Test StatsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fatcat_client.models.stats_response.StatsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
