//! Main binary entry point for fatcat implementation.

#![allow(missing_docs)]

// Imports required by this file.
// extern crate <name of this crate>;
extern crate clap;
extern crate fatcat;
extern crate hyper_openssl;
extern crate iron;
extern crate swagger;

// Imports required by server library.
// extern crate fatcat;
// extern crate swagger;
extern crate chrono;
extern crate futures;
#[macro_use]
extern crate error_chain;

use clap::{App, Arg};
use hyper_openssl::OpensslServer;
use hyper_openssl::openssl::error::ErrorStack;
use hyper_openssl::openssl::ssl::{SslAcceptorBuilder, SslMethod};
use hyper_openssl::openssl::x509::X509_FILETYPE_PEM;
use iron::{Chain, Iron};
use swagger::auth::AllowAllMiddleware;

mod server_lib;

/// Builds an SSL implementation for Simple HTTPS from some hard-coded file names
fn ssl() -> Result<OpensslServer, ErrorStack> {
    let mut ssl = SslAcceptorBuilder::mozilla_intermediate_raw(SslMethod::tls())?;

    // Server authentication
    ssl.set_private_key_file("examples/server-key.pem", X509_FILETYPE_PEM)?;
    ssl.set_certificate_chain_file("examples/server-chain.pem")?;
    ssl.check_private_key()?;

    Ok(OpensslServer::from(ssl.build()))
}

/// Create custom server, wire it to the autogenerated router,
/// and pass it to the web server.
fn main() {
    let matches = App::new("server")
        .arg(
            Arg::with_name("https")
                .long("https")
                .help("Whether to use HTTPS or not"),
        )
        .get_matches();

    let server = server_lib::server().unwrap();
    let router = fatcat::router(server);

    let mut chain = Chain::new(router);
    chain.link_before(fatcat::server::ExtractAuthData);
    // add authentication middlewares into the chain here
    // for the purpose of this example, pretend we have authenticated a user
    chain.link_before(AllowAllMiddleware::new("cosmo"));

    if matches.is_present("https") {
        // Using Simple HTTPS
        Iron::new(chain)
            .https("localhost:8080", ssl().expect("Failed to load SSL keys"))
            .expect("Failed to start HTTPS server");
    } else {
        // Using HTTP
        Iron::new(chain)
            .http("localhost:8080")
            .expect("Failed to start HTTP server");
    }
}
