from fatcat_openapi_client.api_client import ApiClient as ApiClient
from fatcat_openapi_client.exceptions import ApiTypeError as ApiTypeError, ApiValueError as ApiValueError
from fatcat_openapi_client import ReleaseEntity, FileEntity, FilesetEntity, WebcaptureEntity, CreatorEntity, ContainerEntity, WorkEntity, EntityEdit, ChangelogEntry, Editgroup, Editor, EditgroupAnnotation, Success
from typing import Any, List

class DefaultApi:
    api_client: ApiClient
    def __init__(self, api_client: ApiClient | None = ...) -> None: ...
    def accept_editgroup(self, editgroup_id: str, **kwargs) -> Success: ...
    def accept_editgroup_with_http_info(self, editgroup_id: str, **kwargs): ...
    def auth_check(self, **kwargs) -> Success: ...
    def auth_check_with_http_info(self, **kwargs): ...
    def auth_oidc(self, oidc_params: AuthOidc, **kwargs) -> AuthOidcResult: ...
    def auth_oidc_with_http_info(self, oidc_params: AuthOidc, **kwargs): ...
    def create_auth_token(self, editor_id: str, **kwargs) -> AuthTokenResult: ...
    def create_auth_token_with_http_info(self, editor_id: str, **kwargs): ...
    def create_container(self, editgroup_id: str, entity: ContainerEntity, **kwargs) -> EntityEdit: ...
    def create_container_with_http_info(self, editgroup_id: str, entity: ContainerEntity, **kwargs): ...
    def create_container_auto_batch(self, auto_batch, **kwargs) -> Editgroup: ...
    def create_container_auto_batch_with_http_info(self, auto_batch, **kwargs): ...
    def create_creator(self, editgroup_id: str, entity: ContainerEntity, **kwargs) -> EntityEdit: ...
    def create_creator_with_http_info(self, editgroup_id: str, entity: ContainerEntity, **kwargs): ...
    def create_creator_auto_batch(self, auto_batch, **kwargs) -> Editgroup: ...
    def create_creator_auto_batch_with_http_info(self, auto_batch, **kwargs): ...
    def create_editgroup(self, editgroup, **kwargs) -> Editgroup: ...
    def create_editgroup_with_http_info(self, editgroup, **kwargs): ...
    def create_editgroup_annotation(self, editgroup_id: str, annotation: EditgroupAnnotation, **kwargs) -> EditgroupAnnotation: ...
    def create_editgroup_annotation_with_http_info(self, editgroup_id: str, annotation, **kwargs): ...
    def create_file(self, editgroup_id: str, entity: FileEntity, **kwargs) -> EntityEdit: ...
    def create_file_with_http_info(self, editgroup_id: str, entity: FileEntity, **kwargs): ...
    def create_file_auto_batch(self, auto_batch, **kwargs) -> Editgroup: ...
    def create_file_auto_batch_with_http_info(self, auto_batch, **kwargs): ...
    def create_fileset(self, editgroup_id: str, entity: FilesetEntity, **kwargs) -> EntityEdit: ...
    def create_fileset_with_http_info(self, editgroup_id: str, entity: FilesetEntity, **kwargs): ...
    def create_fileset_auto_batch(self, auto_batch, **kwargs) -> Editgroup: ...
    def create_fileset_auto_batch_with_http_info(self, auto_batch, **kwargs): ...
    def create_release(self, editgroup_id: str, entity: ReleaseEntity, **kwargs) -> EntityEdit: ...
    def create_release_with_http_info(self, editgroup_id: str, entity: ReleaseEntity, **kwargs): ...
    def create_release_auto_batch(self, auto_batch, **kwargs) -> Editgroup: ...
    def create_release_auto_batch_with_http_info(self, auto_batch, **kwargs): ...
    def create_webcapture(self, editgroup_id: str, entity: WebcaptureEntity, **kwargs) -> EntityEdit: ...
    def create_webcapture_with_http_info(self, editgroup_id: str, entity: WebcaptureEntity, **kwargs): ...
    def create_webcapture_auto_batch(self, auto_batch, **kwargs) -> Editgroup: ...
    def create_webcapture_auto_batch_with_http_info(self, auto_batch, **kwargs): ...
    def create_work(self, editgroup_id: str, entity: WorkEntity, **kwargs) -> EntityEdit: ...
    def create_work_with_http_info(self, editgroup_id: str, entity: WorkEntity, **kwargs): ...
    def create_work_auto_batch(self, auto_batch, **kwargs) -> Editgroup: ...
    def create_work_auto_batch_with_http_info(self, auto_batch, **kwargs): ...
    def delete_container(self, editgroup_id: str, ident: str, **kwargs) -> EntityEdit: ...
    def delete_container_with_http_info(self, editgroup_id: str, ident: str, **kwargs): ...
    def delete_container_edit(self, editgroup_id: str, edit_id: str, **kwargs) -> Success: ...
    def delete_container_edit_with_http_info(self, editgroup_id: str, edit_id: str, **kwargs): ...
    def delete_creator(self, editgroup_id: str, ident: str, **kwargs) -> EntityEdit: ...
    def delete_creator_with_http_info(self, editgroup_id: str, ident: str, **kwargs): ...
    def delete_creator_edit(self, editgroup_id: str, edit_id: str, **kwargs) -> Success: ...
    def delete_creator_edit_with_http_info(self, editgroup_id: str, edit_id: str, **kwargs): ...
    def delete_file(self, editgroup_id: str, ident: str, **kwargs) -> EntityEdit: ...
    def delete_file_with_http_info(self, editgroup_id: str, ident: str, **kwargs): ...
    def delete_file_edit(self, editgroup_id: str, edit_id: str, **kwargs) -> Success: ...
    def delete_file_edit_with_http_info(self, editgroup_id: str, edit_id: str, **kwargs): ...
    def delete_fileset(self, editgroup_id: str, ident: str, **kwargs) -> EntityEdit: ...
    def delete_fileset_with_http_info(self, editgroup_id: str, ident: str, **kwargs): ...
    def delete_fileset_edit(self, editgroup_id: str, edit_id: str, **kwargs) -> Success: ...
    def delete_fileset_edit_with_http_info(self, editgroup_id: str, edit_id: str, **kwargs): ...
    def delete_release(self, editgroup_id: str, ident: str, **kwargs) -> EntityEdit: ...
    def delete_release_with_http_info(self, editgroup_id: str, ident: str, **kwargs): ...
    def delete_release_edit(self, editgroup_id: str, edit_id: str, **kwargs) -> Success: ...
    def delete_release_edit_with_http_info(self, editgroup_id: str, edit_id: str, **kwargs): ...
    def delete_webcapture(self, editgroup_id: str, ident: str, **kwargs) -> EntityEdit: ...
    def delete_webcapture_with_http_info(self, editgroup_id: str, ident: str, **kwargs): ...
    def delete_webcapture_edit(self, editgroup_id: str, edit_id: str, **kwargs) -> Success: ...
    def delete_webcapture_edit_with_http_info(self, editgroup_id: str, edit_id: str, **kwargs): ...
    def delete_work(self, editgroup_id: str, ident: str, **kwargs) -> EntityEdit: ...
    def delete_work_with_http_info(self, editgroup_id: str, ident: str, **kwargs): ...
    def delete_work_edit(self, editgroup_id: str, edit_id: str, **kwargs) -> Success: ...
    def delete_work_edit_with_http_info(self, editgroup_id: str, edit_id: str, **kwargs): ...
    def get_changelog(self, **kwargs) -> List[ChangelogEntry]: ...
    def get_changelog_with_http_info(self, **kwargs): ...
    def get_changelog_entry(self, index, **kwargs) -> ChangelogEntry: ...
    def get_changelog_entry_with_http_info(self, index, **kwargs): ...
    def get_container(self, ident: str, **kwargs) -> ContainerEntity: ...
    def get_container_with_http_info(self, ident: str, **kwargs): ...
    def get_container_edit(self, edit_id: str, **kwargs) -> EntityEdit: ...
    def get_container_edit_with_http_info(self, edit_id: str, **kwargs): ...
    def get_container_history(self, ident: str, **kwargs) -> List[EntityHistoryEntry]: ...
    def get_container_history_with_http_info(self, ident: str, **kwargs): ...
    def get_container_redirects(self, ident: str, **kwargs) -> List[str]: ...
    def get_container_redirects_with_http_info(self, ident: str, **kwargs): ...
    def get_container_revision(self, rev_id: str, **kwargs) -> ContainerEntity: ...
    def get_container_revision_with_http_info(self, rev_id: str, **kwargs): ...
    def get_creator(self, ident: str, **kwargs) -> CreatorEntity: ...
    def get_creator_with_http_info(self, ident: str, **kwargs): ...
    def get_creator_edit(self, edit_id: str, **kwargs) -> EntityEdit: ...
    def get_creator_edit_with_http_info(self, edit_id: str, **kwargs): ...
    def get_creator_history(self, ident: str, **kwargs) -> List[EntityHistoryEntry]: ...
    def get_creator_history_with_http_info(self, ident: str, **kwargs): ...
    def get_creator_redirects(self, ident: str, **kwargs) -> List[str]: ...
    def get_creator_redirects_with_http_info(self, ident: str, **kwargs): ...
    def get_creator_releases(self, ident: str, **kwargs) -> List[ReleaseEntity]: ...
    def get_creator_releases_with_http_info(self, ident: str, **kwargs): ...
    def get_creator_revision(self, rev_id: str, **kwargs) -> CreatorEntity: ...
    def get_creator_revision_with_http_info(self, rev_id: str, **kwargs): ...
    def get_editgroup(self, editgroup_id: str, **kwargs) -> Editgroup: ...
    def get_editgroup_with_http_info(self, editgroup_id: str, **kwargs): ...
    def get_editgroup_annotations(self, editgroup_id: str, **kwargs) -> List[EditgroupAnnotation]: ...
    def get_editgroup_annotations_with_http_info(self, editgroup_id: str, **kwargs): ...
    def get_editgroups_reviewable(self, **kwargs) -> List[Editgroup]: ...
    def get_editgroups_reviewable_with_http_info(self, **kwargs): ...
    def get_editor(self, editor_id: str, **kwargs) -> Editor: ...
    def get_editor_with_http_info(self, editor_id: str, **kwargs): ...
    def get_editor_annotations(self, editor_id: str, **kwargs) -> List[EditgroupAnnotation]: ...
    def get_editor_annotations_with_http_info(self, editor_id: str, **kwargs): ...
    def get_editor_editgroups(self, editor_id: str, **kwargs) -> List[Editgroup]: ...
    def get_editor_editgroups_with_http_info(self, editor_id: str, **kwargs): ...
    def get_file(self, ident: str, **kwargs) -> FileEntity: ...
    def get_file_with_http_info(self, ident: str, **kwargs): ...
    def get_file_edit(self, edit_id: str, **kwargs) -> EntityEdit: ...
    def get_file_edit_with_http_info(self, edit_id: str, **kwargs): ...
    def get_file_history(self, ident: str, **kwargs) -> List[EntityHistoryEntry]: ...
    def get_file_history_with_http_info(self, ident: str, **kwargs): ...
    def get_file_redirects(self, ident: str, **kwargs) -> List[str]: ...
    def get_file_redirects_with_http_info(self, ident: str, **kwargs): ...
    def get_file_revision(self, rev_id: str, **kwargs) -> FileEntity: ...
    def get_file_revision_with_http_info(self, rev_id: str, **kwargs): ...
    def get_fileset(self, ident: str, **kwargs) -> FilesetEntity: ...
    def get_fileset_with_http_info(self, ident: str, **kwargs): ...
    def get_fileset_edit(self, edit_id: str, **kwargs) -> EntityEdit: ...
    def get_fileset_edit_with_http_info(self, edit_id: str, **kwargs): ...
    def get_fileset_history(self, ident: str, **kwargs) -> List[EntityHistoryEntry]: ...
    def get_fileset_history_with_http_info(self, ident: str, **kwargs): ...
    def get_fileset_redirects(self, ident: str, **kwargs) -> List[str]: ...
    def get_fileset_redirects_with_http_info(self, ident: str, **kwargs): ...
    def get_fileset_revision(self, rev_id: str, **kwargs) -> FilesetEntity: ...
    def get_fileset_revision_with_http_info(self, rev_id: str, **kwargs): ...
    def get_release(self, ident: str, **kwargs) -> ReleaseEntity: ...
    def get_release_with_http_info(self, ident: str, **kwargs): ...
    def get_release_edit(self, edit_id: str, **kwargs) -> EntityEdit: ...
    def get_release_edit_with_http_info(self, edit_id: str, **kwargs): ...
    def get_release_files(self, ident: str, **kwargs) -> List[FileEntity]: ...
    def get_release_files_with_http_info(self, ident: str, **kwargs): ...
    def get_release_filesets(self, ident: str, **kwargs) -> List[FilesetEntity]: ...
    def get_release_filesets_with_http_info(self, ident: str, **kwargs): ...
    def get_release_history(self, ident: str, **kwargs) -> List[EntityHistoryEntry]: ...
    def get_release_history_with_http_info(self, ident: str, **kwargs): ...
    def get_release_redirects(self, ident: str, **kwargs) -> List[str]: ...
    def get_release_redirects_with_http_info(self, ident: str, **kwargs): ...
    def get_release_revision(self, rev_id: str, **kwargs) -> ReleaseEntity: ...
    def get_release_revision_with_http_info(self, rev_id: str, **kwargs): ...
    def get_release_webcaptures(self, ident: str, **kwargs) -> List[WebcaptureEntity]: ...
    def get_release_webcaptures_with_http_info(self, ident: str, **kwargs): ...
    def get_webcapture(self, ident: str, **kwargs) -> WebcaptureEntity: ...
    def get_webcapture_with_http_info(self, ident: str, **kwargs): ...
    def get_webcapture_edit(self, edit_id: str, **kwargs) -> EntityEdit: ...
    def get_webcapture_edit_with_http_info(self, edit_id: str, **kwargs): ...
    def get_webcapture_history(self, ident: str, **kwargs) -> List[EntityHistoryEntry]: ...
    def get_webcapture_history_with_http_info(self, ident: str, **kwargs): ...
    def get_webcapture_redirects(self, ident: str, **kwargs) -> List[str]: ...
    def get_webcapture_redirects_with_http_info(self, ident: str, **kwargs): ...
    def get_webcapture_revision(self, rev_id: str, **kwargs) -> WebcaptureEntity: ...
    def get_webcapture_revision_with_http_info(self, rev_id: str, **kwargs): ...
    def get_work(self, ident: str, **kwargs) -> WorkEntity: ...
    def get_work_with_http_info(self, ident: str, **kwargs): ...
    def get_work_edit(self, edit_id: str, **kwargs) -> EntityEdit: ...
    def get_work_edit_with_http_info(self, edit_id: str, **kwargs): ...
    def get_work_history(self, ident: str, **kwargs) -> List[EntityHistoryEntry]: ...
    def get_work_history_with_http_info(self, ident: str, **kwargs): ...
    def get_work_redirects(self, ident: str, **kwargs) -> List[str]: ...
    def get_work_redirects_with_http_info(self, ident: str, **kwargs): ...
    def get_work_releases(self, ident: str, **kwargs) -> List[ReleaseEntity]: ...
    def get_work_releases_with_http_info(self, ident: str, **kwargs): ...
    def get_work_revision(self, rev_id: str, **kwargs) -> WorkEntity: ...
    def get_work_revision_with_http_info(self, rev_id: str, **kwargs): ...
    def lookup_container(self, **kwargs) -> ContainerEntity: ...
    def lookup_container_with_http_info(self, **kwargs): ...
    def lookup_creator(self, **kwargs) -> CreatorEntity: ...
    def lookup_creator_with_http_info(self, **kwargs): ...
    def lookup_editor(self, **kwargs) -> Editor: ...
    def lookup_editor_with_http_info(self, **kwargs): ...
    def lookup_file(self, **kwargs) -> FileEntity: ...
    def lookup_file_with_http_info(self, **kwargs): ...
    def lookup_release(self, **kwargs) -> ReleaseEntity: ...
    def lookup_release_with_http_info(self, **kwargs): ...
    def update_container(self, editgroup_id: str, ident: str, entity: ContainerEntity, **kwargs) -> EntityEdit: ...
    def update_container_with_http_info(self, editgroup_id: str, ident: str, entity: ContainerEntity, **kwargs): ...
    def update_creator(self, editgroup_id: str, ident: str, entity: CreatorEntity, **kwargs) -> EntityEdit: ...
    def update_creator_with_http_info(self, editgroup_id: str, ident: str, entity: CreatorEntity, **kwargs): ...
    def update_editgroup(self, editgroup_id: str, editgroup: Editgroup, **kwargs) -> Editgroup: ...
    def update_editgroup_with_http_info(self, editgroup_id: str, editgroup: Editgroup, **kwargs): ...
    def update_editor(self, editor_id: str, editor: Editor, **kwargs) -> Editor: ...
    def update_editor_with_http_info(self, editor_id: str, editor: Editor, **kwargs): ...
    def update_file(self, editgroup_id: str, ident: str, entity: FileEntity, **kwargs) -> EntityEdit: ...
    def update_file_with_http_info(self, editgroup_id: str, ident: str, entity: FileEntity, **kwargs): ...
    def update_fileset(self, editgroup_id: str, ident: str, entity: FilesetEntity, **kwargs) -> EntityEdit: ...
    def update_fileset_with_http_info(self, editgroup_id: str, ident: str, entity: FilesetEntity, **kwargs): ...
    def update_release(self, editgroup_id: str, ident: str, entity: ReleaseEntity, **kwargs) -> EntityEdit: ...
    def update_release_with_http_info(self, editgroup_id: str, ident: str, entity: ReleaseEntity, **kwargs): ...
    def update_webcapture(self, editgroup_id: str, ident: str, entity: WebcaptureEntity, **kwargs) -> EntityEdit: ...
    def update_webcapture_with_http_info(self, editgroup_id: str, ident: str, entity: WebcaptureEntity, **kwargs): ...
    def update_work(self, editgroup_id: str, ident: str, entity: WorkEntity, **kwargs) -> EntityEdit: ...
    def update_work_with_http_info(self, editgroup_id: str, ident: str, entity: WorkEntity, **kwargs): ...
