
-- in opposite order as up.sql

DROP TABLE IF EXISTS release_contrib CASCADE;
DROP TABLE IF EXISTS refs_blob CASCADE;
DROP TABLE IF EXISTS release_ref CASCADE;
DROP TABLE IF EXISTS file_rev_release CASCADE;
DROP TABLE IF EXISTS fileset_rev_release CASCADE;
DROP TABLE IF EXISTS webcapture_rev_release CASCADE;

DROP TABLE IF EXISTS work_rev CASCADE;
DROP TABLE IF EXISTS work_ident CASCADE;
DROP TABLE IF EXISTS work_edit CASCADE;

DROP TABLE IF EXISTS release_rev CASCADE;
DROP TABLE IF EXISTS release_ident CASCADE;
DROP TABLE IF EXISTS release_edit CASCADE;
DROP TABLE IF EXISTS release_rev_abstract CASCADE;

DROP TABLE IF EXISTS file_rev CASCADE;
DROP TABLE IF EXISTS file_ident CASCADE;
DROP TABLE IF EXISTS file_edit CASCADE;
DROP TABLE IF EXISTS file_rev_url CASCADE;

DROP TABLE IF EXISTS fileset_rev CASCADE;
DROP TABLE IF EXISTS fileset_ident CASCADE;
DROP TABLE IF EXISTS fileset_edit CASCADE;
DROP TABLE IF EXISTS fileset_rev_file CASCADE;
DROP TABLE IF EXISTS fileset_rev_url CASCADE;

DROP TABLE IF EXISTS webcapture_rev CASCADE;
DROP TABLE IF EXISTS webcapture_ident CASCADE;
DROP TABLE IF EXISTS webcapture_edit CASCADE;
DROP TABLE IF EXISTS webcapture_rev_cdx CASCADE;
DROP TABLE IF EXISTS webcapture_rev_url CASCADE;

DROP TABLE IF EXISTS container_rev CASCADE;
DROP TABLE IF EXISTS container_ident CASCADE;
DROP TABLE IF EXISTS container_edit CASCADE;

DROP TABLE IF EXISTS creator_rev CASCADE;
DROP TABLE IF EXISTS creator_ident CASCADE;
DROP TABLE IF EXISTS creator_edit CASCADE;

DROP TABLE IF EXISTS abstracts CASCADE;
DROP TABLE IF EXISTS auth_oidc CASCADE;
DROP TABLE IF EXISTS editor CASCADE;
DROP TABLE IF EXISTS editgroup_annotation CASCADE;
DROP TABLE IF EXISTS editgroup CASCADE;
DROP TABLE IF EXISTS changelog CASCADE;
