# coding: utf-8

"""
    fatcat

    A scalable, versioned, API-oriented catalog of bibliographic entities and file metadata  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fatcat_client
from fatcat_client.models.release_contrib import ReleaseContrib  # noqa: E501
from fatcat_client.rest import ApiException


class TestReleaseContrib(unittest.TestCase):
    """ReleaseContrib unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReleaseContrib(self):
        """Test ReleaseContrib"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fatcat_client.models.release_contrib.ReleaseContrib()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
