# coding: utf-8

"""
    fatcat

    A scalable, versioned, API-oriented catalog of bibliographic entities and file metadata  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fatcat_client
from fatcat_client.api.default_api import DefaultApi  # noqa: E501
from fatcat_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = fatcat_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_container_batch_post(self):
        """Test case for container_batch_post

        """
        pass

    def test_container_id_get(self):
        """Test case for container_id_get

        """
        pass

    def test_container_lookup_get(self):
        """Test case for container_lookup_get

        """
        pass

    def test_container_post(self):
        """Test case for container_post

        """
        pass

    def test_creator_batch_post(self):
        """Test case for creator_batch_post

        """
        pass

    def test_creator_id_get(self):
        """Test case for creator_id_get

        """
        pass

    def test_creator_lookup_get(self):
        """Test case for creator_lookup_get

        """
        pass

    def test_creator_post(self):
        """Test case for creator_post

        """
        pass

    def test_editgroup_id_accept_post(self):
        """Test case for editgroup_id_accept_post

        """
        pass

    def test_editgroup_id_get(self):
        """Test case for editgroup_id_get

        """
        pass

    def test_editgroup_post(self):
        """Test case for editgroup_post

        """
        pass

    def test_editor_username_changelog_get(self):
        """Test case for editor_username_changelog_get

        """
        pass

    def test_editor_username_get(self):
        """Test case for editor_username_get

        """
        pass

    def test_file_batch_post(self):
        """Test case for file_batch_post

        """
        pass

    def test_file_id_get(self):
        """Test case for file_id_get

        """
        pass

    def test_file_lookup_get(self):
        """Test case for file_lookup_get

        """
        pass

    def test_file_post(self):
        """Test case for file_post

        """
        pass

    def test_release_batch_post(self):
        """Test case for release_batch_post

        """
        pass

    def test_release_id_get(self):
        """Test case for release_id_get

        """
        pass

    def test_release_lookup_get(self):
        """Test case for release_lookup_get

        """
        pass

    def test_release_post(self):
        """Test case for release_post

        """
        pass

    def test_work_batch_post(self):
        """Test case for work_batch_post

        """
        pass

    def test_work_id_get(self):
        """Test case for work_id_get

        """
        pass

    def test_work_post(self):
        """Test case for work_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
