from fatcat_openapi_client import rest as rest
from fatcat_openapi_client.configuration import Configuration as Configuration
from fatcat_openapi_client.exceptions import ApiValueError as ApiValueError
from typing import Any

class ApiClient:
    PRIMITIVE_TYPES: Any
    NATIVE_TYPES_MAPPING: Any
    configuration: Any
    pool_threads: Any
    rest_client: Any
    default_headers: Any
    cookie: Any
    def __init__(self, configuration: Configuration | None = ..., header_name: Any | None = ..., header_value: Any | None = ..., cookie: Any | None = ..., pool_threads: int = ...) -> None: ...
    def __del__(self) -> None: ...
    @property
    def pool(self): ...
    @property
    def user_agent(self): ...
    @user_agent.setter
    def user_agent(self, value) -> None: ...
    def set_default_header(self, header_name, header_value) -> None: ...
    def sanitize_for_serialization(self, obj): ...
    def deserialize(self, response, response_type): ...
    def call_api(self, resource_path, method, path_params: Any | None = ..., query_params: Any | None = ..., header_params: Any | None = ..., body: Any | None = ..., post_params: Any | None = ..., files: Any | None = ..., response_type: Any | None = ..., auth_settings: Any | None = ..., async_req: Any | None = ..., _return_http_data_only: Any | None = ..., collection_formats: Any | None = ..., _preload_content: bool = ..., _request_timeout: Any | None = ..., _host: Any | None = ...): ...
    def request(self, method, url, query_params: Any | None = ..., headers: Any | None = ..., post_params: Any | None = ..., body: Any | None = ..., _preload_content: bool = ..., _request_timeout: Any | None = ...): ...
    def parameters_to_tuples(self, params, collection_formats): ...
    def files_parameters(self, files: Any | None = ...): ...
    def select_header_accept(self, accepts): ...
    def select_header_content_type(self, content_types): ...
    def update_params_for_auth(self, headers, querys, auth_settings) -> None: ...
