from typing import Any

class AuthOidc:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, provider: Any | None = ..., sub: Any | None = ..., iss: Any | None = ..., preferred_username: Any | None = ...) -> None: ...
    @property
    def provider(self): ...
    @provider.setter
    def provider(self, provider) -> None: ...
    @property
    def sub(self): ...
    @sub.setter
    def sub(self, sub) -> None: ...
    @property
    def iss(self): ...
    @iss.setter
    def iss(self, iss) -> None: ...
    @property
    def preferred_username(self): ...
    @preferred_username.setter
    def preferred_username(self, preferred_username) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
