from typing import Any
import datetime
from fatcat_openapi_client import Editgroup

class ChangelogEntry:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, index: Any | None = ..., editgroup_id: Any | None = ..., timestamp: Any | None = ..., editgroup: Any | None = ...) -> None: ...
    @property
    def index(self) -> int: ...
    @index.setter
    def index(self, index: int) -> None: ...
    @property
    def editgroup_id(self) -> str: ...
    @editgroup_id.setter
    def editgroup_id(self, editgroup_id: str) -> None: ...
    @property
    def timestamp(self) -> datetime.datetime: ...
    @timestamp.setter
    def timestamp(self, timestamp: datetime.datetime) -> None: ...
    @property
    def editgroup(self) -> Editgroup: ...
    @editgroup.setter
    def editgroup(self, editgroup: Editgroup) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
