from typing import Any

class ContainerAutoBatch:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, editgroup: Editgroup = ..., entity_list: List[ContainerEntity] = ...) -> None: ...
    @property
    def editgroup(self) -> Editgroup: ...
    @editgroup.setter
    def editgroup(self, editgroup: Editgroup) -> None: ...
    @property
    def entity_list(self) -> List[ContainerEntity]: ...
    @entity_list.setter
    def entity_list(self, entity_list: List[ContainerEntity]) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
