from typing import Any, Optional, Dict, List

class ContainerEntity:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, state: Optional[str] = ..., ident: Optional[str] = ..., revision: Optional[str] = ..., redirect: Optional[str] = ..., extra: Any | None = ..., edit_extra: Any | None = ..., name: Optional[str] = ..., container_type: Optional[str] = ..., publication_status: Optional[str] = ..., publisher: Optional[str] = ..., issnl: Optional[str] = ..., issne: Optional[str] = ..., issnp: Optional[str] = ..., wikidata_qid: Optional[str] = ...) -> None: ...
    @property
    def state(self) -> Optional[str]: ...
    @state.setter
    def state(self, state: Optional[str]) -> None: ...
    @property
    def ident(self) -> Optional[str]: ...
    @ident.setter
    def ident(self, ident: Optional[str]) -> None: ...
    @property
    def revision(self) -> Optional[str]: ...
    @revision.setter
    def revision(self, revision: Optional[str]) -> None: ...
    @property
    def redirect(self) -> Optional[str]: ...
    @redirect.setter
    def redirect(self, redirect: Optional[str]) -> None: ...
    @property
    def extra(self) -> Optional[Dict[str, Any]]: ...
    @extra.setter
    def extra(self, extra: Optional[Dict[str, Any]]) -> None: ...
    @property
    def edit_extra(self) -> Optional[Dict[str, Any]]: ...
    @edit_extra.setter
    def edit_extra(self, edit_extra: Optional[Dict[str, Any]]) -> None: ...
    @property
    def name(self) -> Optional[str]: ...
    @name.setter
    def name(self, name: Optional[str]) -> None: ...
    @property
    def container_type(self) -> Optional[str]: ...
    @container_type.setter
    def container_type(self, container_type: Optional[str]) -> None: ...
    @property
    def publication_status(self) -> Optional[str]: ...
    @publication_status.setter
    def publication_status(self, publication_status: Optional[str]) -> None: ...
    @property
    def publisher(self) -> Optional[str]: ...
    @publisher.setter
    def publisher(self, publisher: Optional[str]) -> None: ...
    @property
    def issnl(self) -> Optional[str]: ...
    @issnl.setter
    def issnl(self, issnl: Optional[str]) -> None: ...
    @property
    def issne(self) -> Optional[str]: ...
    @issne.setter
    def issne(self, issne: Optional[str]) -> None: ...
    @property
    def issnp(self) -> Optional[str]: ...
    @issnp.setter
    def issnp(self, issnp: Optional[str]) -> None: ...
    @property
    def wikidata_qid(self) -> Optional[str]: ...
    @wikidata_qid.setter
    def wikidata_qid(self, wikidata_qid: Optional[str]) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
