from typing import Any, Optional, Dict, List
from fatcat_openapi_client import ReleaseEntity

class CreatorEntity:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, state: Optional[str] = ..., ident: Optional[str] = ..., revision: Optional[str]= ..., redirect: Optional[str]= ..., extra: Any | None = ..., edit_extra: Any | None = ..., display_name: Optional[str] = ..., given_name: Optional[str] = ..., surname: Optional[str] = ..., orcid: Optional[str] = ..., wikidata_qid: Optional[str]= ...) -> None: ...
    @property
    def state(self) -> Optional[str]: ...
    @state.setter
    def state(self, state: Optional[str]) -> None: ...
    @property
    def ident(self) -> Optional[str]: ...
    @ident.setter
    def ident(self, ident: Optional[str]) -> None: ...
    @property
    def revision(self) -> Optional[str]: ...
    @revision.setter
    def revision(self, revision: Optional[str]) -> None: ...
    @property
    def redirect(self) -> Optional[str]: ...
    @redirect.setter
    def redirect(self, redirect: Optional[str]) -> None: ...
    @property
    def extra(self) -> Optional[Dict[str, Any]]: ...
    @extra.setter
    def extra(self, extra: Optional[Dict[str, Any]]) -> None: ...
    @property
    def edit_extra(self) -> Optional[Dict[str, Any]]: ...
    @edit_extra.setter
    def edit_extra(self, edit_extra: Optional[Dict[str, Any]]) -> None: ...
    @property
    def display_name(self) -> Optional[str]: ...
    @display_name.setter
    def display_name(self, display_name: Optional[str]) -> None: ...
    @property
    def given_name(self) -> Optional[str]: ...
    @given_name.setter
    def given_name(self, given_name: Optional[str]) -> None: ...
    @property
    def surname(self) -> Optional[str]: ...
    @surname.setter
    def surname(self, surname: Optional[str]) -> None: ...
    @property
    def orcid(self) -> Optional[str]: ...
    @orcid.setter
    def orcid(self, orcid: Optional[str]) -> None: ...
    @property
    def wikidata_qid(self) -> Optional[str]: ...
    @wikidata_qid.setter
    def wikidata_qid(self, wikidata_qid: Optional[str]) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
