from typing import Any

class Editor:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, editor_id: Any | None = ..., username: Any | None = ..., is_admin: Any | None = ..., is_bot: Any | None = ..., is_active: Any | None = ...) -> None: ...
    @property
    def editor_id(self): ...
    @editor_id.setter
    def editor_id(self, editor_id) -> None: ...
    @property
    def username(self): ...
    @username.setter
    def username(self, username) -> None: ...
    @property
    def is_admin(self): ...
    @is_admin.setter
    def is_admin(self, is_admin) -> None: ...
    @property
    def is_bot(self): ...
    @is_bot.setter
    def is_bot(self, is_bot) -> None: ...
    @property
    def is_active(self): ...
    @is_active.setter
    def is_active(self, is_active) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
