from typing import Any

class EditgroupAnnotation:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, annotation_id: Any | None = ..., editgroup_id: Any | None = ..., editor_id: Any | None = ..., editor: Any | None = ..., created: Any | None = ..., comment_markdown: Any | None = ..., extra: Any | None = ...) -> None: ...
    @property
    def annotation_id(self): ...
    @annotation_id.setter
    def annotation_id(self, annotation_id) -> None: ...
    @property
    def editgroup_id(self): ...
    @editgroup_id.setter
    def editgroup_id(self, editgroup_id) -> None: ...
    @property
    def editor_id(self): ...
    @editor_id.setter
    def editor_id(self, editor_id) -> None: ...
    @property
    def editor(self): ...
    @editor.setter
    def editor(self, editor) -> None: ...
    @property
    def created(self): ...
    @created.setter
    def created(self, created) -> None: ...
    @property
    def comment_markdown(self): ...
    @comment_markdown.setter
    def comment_markdown(self, comment_markdown) -> None: ...
    @property
    def extra(self): ...
    @extra.setter
    def extra(self, extra) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
