from typing import Any

class EntityHistoryEntry:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, edit: Any | None = ..., editgroup: Any | None = ..., changelog_entry: Any | None = ...) -> None: ...
    @property
    def edit(self): ...
    @edit.setter
    def edit(self, edit) -> None: ...
    @property
    def editgroup(self): ...
    @editgroup.setter
    def editgroup(self, editgroup) -> None: ...
    @property
    def changelog_entry(self): ...
    @changelog_entry.setter
    def changelog_entry(self, changelog_entry) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
