from typing import Any

class FilesetFile:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, path: Any | None = ..., size: Any | None = ..., md5: Any | None = ..., sha1: Any | None = ..., sha256: Any | None = ..., mimetype: Any | None = ..., extra: Any | None = ...) -> None: ...
    @property
    def path(self): ...
    @path.setter
    def path(self, path) -> None: ...
    @property
    def size(self): ...
    @size.setter
    def size(self, size) -> None: ...
    @property
    def md5(self): ...
    @md5.setter
    def md5(self, md5) -> None: ...
    @property
    def sha1(self): ...
    @sha1.setter
    def sha1(self, sha1) -> None: ...
    @property
    def sha256(self): ...
    @sha256.setter
    def sha256(self, sha256) -> None: ...
    @property
    def mimetype(self): ...
    @mimetype.setter
    def mimetype(self, mimetype) -> None: ...
    @property
    def extra(self): ...
    @extra.setter
    def extra(self, extra) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
