from typing import Any

class FilesetAutoBatch:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, editgroup: Any | None = ..., entity_list: Any | None = ...) -> None: ...
    @property
    def editgroup(self): ...
    @editgroup.setter
    def editgroup(self, editgroup) -> None: ...
    @property
    def entity_list(self): ...
    @entity_list.setter
    def entity_list(self, entity_list) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
