from typing import Any

class ReleaseAbstract:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, sha1: Any | None = ..., content: Any | None = ..., mimetype: Any | None = ..., lang: Any | None = ...) -> None: ...
    @property
    def sha1(self): ...
    @sha1.setter
    def sha1(self, sha1) -> None: ...
    @property
    def content(self): ...
    @content.setter
    def content(self, content) -> None: ...
    @property
    def mimetype(self): ...
    @mimetype.setter
    def mimetype(self, mimetype) -> None: ...
    @property
    def lang(self): ...
    @lang.setter
    def lang(self, lang) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
