from typing import Any

class ReleaseRef:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, index: Any | None = ..., target_release_id: Any | None = ..., extra: Any | None = ..., key: Any | None = ..., year: Any | None = ..., container_name: Any | None = ..., title: Any | None = ..., locator: Any | None = ...) -> None: ...
    @property
    def index(self): ...
    @index.setter
    def index(self, index) -> None: ...
    @property
    def target_release_id(self): ...
    @target_release_id.setter
    def target_release_id(self, target_release_id) -> None: ...
    @property
    def extra(self): ...
    @extra.setter
    def extra(self, extra) -> None: ...
    @property
    def key(self): ...
    @key.setter
    def key(self, key) -> None: ...
    @property
    def year(self): ...
    @year.setter
    def year(self, year) -> None: ...
    @property
    def container_name(self): ...
    @container_name.setter
    def container_name(self, container_name) -> None: ...
    @property
    def title(self): ...
    @title.setter
    def title(self, title) -> None: ...
    @property
    def locator(self): ...
    @locator.setter
    def locator(self, locator) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
