from typing import Any, Optional, Dict, List
from fatcat_openapi_client import FileEntity, FilesetEntity, WebcaptureEntity

class ReleaseEntity:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, state: Optional[str] = ..., ident: Optional[str] = ..., revision: Optional[str] = ..., redirect: Optional[str] = ..., extra: Any | None = ..., edit_extra: Any | None = ..., title: Optional[str] = ..., subtitle: Optional[str] = ..., original_title: Optional[str] = ..., work_id: Optional[str] = ..., container: Any | None = ..., files: Any | None = ..., filesets: Any | None = ..., webcaptures: Any | None = ..., container_id: Optional[str] = ..., release_type: Optional[str] = ..., release_stage: Optional[str] = ..., release_date: Any | None = ..., release_year: Any | None = ..., withdrawn_status: Optional[str] = ..., withdrawn_date: Any | None = ..., withdrawn_year: Any | None = ..., ext_ids: Any | None = ..., volume: Optional[str] = ..., issue: Optional[str] = ..., pages: Optional[str] = ..., number: Optional[str] = ..., version: Optional[str] = ..., publisher: Optional[str] = ..., language: Optional[str] = ..., license_slug: Optional[str] = ..., contribs: Any | None = ..., refs: Any | None = ..., abstracts: Any | None = ...) -> None: ...
    @property
    def state(self) -> Optional[str]: ...
    @state.setter
    def state(self, state: Optional[str]) -> None: ...
    @property
    def ident(self) -> Optional[str]: ...
    @ident.setter
    def ident(self, ident: Optional[str]) -> None: ...
    @property
    def revision(self) -> Optional[str]: ...
    @revision.setter
    def revision(self, revision: Optional[str]) -> None: ...
    @property
    def redirect(self) -> Optional[str]: ...
    @redirect.setter
    def redirect(self, redirect: Optional[str]) -> None: ...
    @property
    def extra(self) -> Optional[Dict[str, Any]]: ...
    @extra.setter
    def extra(self, extra: Optional[Dict[str, Any]]) -> None: ...
    @property
    def edit_extra(self) -> Optional[Dict[str, Any]]: ...
    @edit_extra.setter
    def edit_extra(self, edit_extra: Optional[Dict[str, Any]]) -> None: ...
    @property
    def title(self) -> Optional[str]: ...
    @title.setter
    def title(self, title: Optional[str]) -> None: ...
    @property
    def subtitle(self): Optional[str]: ...
    @subtitle.setter
    def subtitle(self, subtitle: Optional[str]) -> None: ...
    @property
    def original_title(self) -> Optional[str]: ...
    @original_title.setter
    def original_title(self, original_title: Optional[str]) -> None: ...
    @property
    def work_id(self) -> Optional[str]: ...
    @work_id.setter
    def work_id(self, work_id: Optional[str]) -> None: ...
    @property
    def container(self): ...
    @container.setter
    def container(self, container) -> None: ...
    @property
    def files(self): ...
    @files.setter
    def files(self, files) -> None: ...
    @property
    def filesets(self): ...
    @filesets.setter
    def filesets(self, filesets) -> None: ...
    @property
    def webcaptures(self): ...
    @webcaptures.setter
    def webcaptures(self, webcaptures) -> None: ...
    @property
    def container_id(self) -> Optional[str]: ...
    @container_id.setter
    def container_id(self, container_id: Optional[str]) -> None: ...
    @property
    def release_type(self) -> Optional[str]: ...
    @release_type.setter
    def release_type(self, release_type: Optional[str]) -> None: ...
    @property
    def release_stage(self) -> Optional[str]: ...
    @release_stage.setter
    def release_stage(self, release_stage: Optional[str]) -> None: ...
    @property
    def release_date(self): ...
    @release_date.setter
    def release_date(self, release_date) -> None: ...
    @property
    def release_year(self): ...
    @release_year.setter
    def release_year(self, release_year) -> None: ...
    @property
    def withdrawn_status(self) -> Optional[str]: ...
    @withdrawn_status.setter
    def withdrawn_status(self, withdrawn_status: Optional[str]) -> None: ...
    @property
    def withdrawn_date(self): ...
    @withdrawn_date.setter
    def withdrawn_date(self, withdrawn_date) -> None: ...
    @property
    def withdrawn_year(self): ...
    @withdrawn_year.setter
    def withdrawn_year(self, withdrawn_year) -> None: ...
    @property
    def ext_ids(self): ...
    @ext_ids.setter
    def ext_ids(self, ext_ids) -> None: ...
    @property
    def volume(self) -> Optional[str]: ...
    @volume.setter
    def volume(self, volume: Optional[str]) -> None: ...
    @property
    def issue(self) -> Optional[str]: ...
    @issue.setter
    def issue(self, issue: Optional[str]) -> None: ...
    @property
    def pages(self) -> Optional[str]: ...
    @pages.setter
    def pages(self, pages: Optional[str]) -> None: ...
    @property
    def number(self) -> Optional[str]: ...
    @number.setter
    def number(self, number: Optional[str]) -> None: ...
    @property
    def version(self) -> Optional[str]: ...
    @version.setter
    def version(self, version: Optional[str]) -> None: ...
    @property
    def publisher(self) -> Optional[str]: ...
    @publisher.setter
    def publisher(self, publisher: Optional[str]) -> None: ...
    @property
    def language(self) -> Optional[str]: ...
    @language.setter
    def language(self, language: Optional[str]) -> None: ...
    @property
    def license_slug(self) -> Optional[str]: ...
    @license_slug.setter
    def license_slug(self, license_slug: Optional[str]) -> None: ...
    @property
    def contribs(self): ...
    @contribs.setter
    def contribs(self, contribs) -> None: ...
    @property
    def refs(self): ...
    @refs.setter
    def refs(self, refs) -> None: ...
    @property
    def abstracts(self): ...
    @abstracts.setter
    def abstracts(self, abstracts) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
