from typing import Any

class ReleaseExtIds:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, doi: Any | None = ..., wikidata_qid: Any | None = ..., isbn13: Any | None = ..., pmid: Any | None = ..., pmcid: Any | None = ..., core: Any | None = ..., arxiv: Any | None = ..., jstor: Any | None = ..., ark: Any | None = ..., mag: Any | None = ..., doaj: Any | None = ..., dblp: Any | None = ..., oai: Any | None = ..., hdl: Any | None = ...) -> None: ...
    @property
    def doi(self): ...
    @doi.setter
    def doi(self, doi) -> None: ...
    @property
    def wikidata_qid(self): ...
    @wikidata_qid.setter
    def wikidata_qid(self, wikidata_qid) -> None: ...
    @property
    def isbn13(self): ...
    @isbn13.setter
    def isbn13(self, isbn13) -> None: ...
    @property
    def pmid(self): ...
    @pmid.setter
    def pmid(self, pmid) -> None: ...
    @property
    def pmcid(self): ...
    @pmcid.setter
    def pmcid(self, pmcid) -> None: ...
    @property
    def core(self): ...
    @core.setter
    def core(self, core) -> None: ...
    @property
    def arxiv(self): ...
    @arxiv.setter
    def arxiv(self, arxiv) -> None: ...
    @property
    def jstor(self): ...
    @jstor.setter
    def jstor(self, jstor) -> None: ...
    @property
    def ark(self): ...
    @ark.setter
    def ark(self, ark) -> None: ...
    @property
    def mag(self): ...
    @mag.setter
    def mag(self, mag) -> None: ...
    @property
    def doaj(self): ...
    @doaj.setter
    def doaj(self, doaj) -> None: ...
    @property
    def dblp(self): ...
    @dblp.setter
    def dblp(self, dblp) -> None: ...
    @property
    def oai(self): ...
    @oai.setter
    def oai(self, oai) -> None: ...
    @property
    def hdl(self): ...
    @hdl.setter
    def hdl(self, hdl) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
