from typing import Any

class ReleaseEntity:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, state: Any | None = ..., ident: Any | None = ..., revision: Any | None = ..., redirect: Any | None = ..., extra: Any | None = ..., edit_extra: Any | None = ..., title: Any | None = ..., subtitle: Any | None = ..., original_title: Any | None = ..., work_id: Any | None = ..., container: Any | None = ..., files: Any | None = ..., filesets: Any | None = ..., webcaptures: Any | None = ..., container_id: Any | None = ..., release_type: Any | None = ..., release_stage: Any | None = ..., release_date: Any | None = ..., release_year: Any | None = ..., withdrawn_status: Any | None = ..., withdrawn_date: Any | None = ..., withdrawn_year: Any | None = ..., ext_ids: Any | None = ..., volume: Any | None = ..., issue: Any | None = ..., pages: Any | None = ..., number: Any | None = ..., version: Any | None = ..., publisher: Any | None = ..., language: Any | None = ..., license_slug: Any | None = ..., contribs: Any | None = ..., refs: Any | None = ..., abstracts: Any | None = ...) -> None: ...
    @property
    def state(self): ...
    @state.setter
    def state(self, state) -> None: ...
    @property
    def ident(self): ...
    @ident.setter
    def ident(self, ident) -> None: ...
    @property
    def revision(self): ...
    @revision.setter
    def revision(self, revision) -> None: ...
    @property
    def redirect(self): ...
    @redirect.setter
    def redirect(self, redirect) -> None: ...
    @property
    def extra(self): ...
    @extra.setter
    def extra(self, extra) -> None: ...
    @property
    def edit_extra(self): ...
    @edit_extra.setter
    def edit_extra(self, edit_extra) -> None: ...
    @property
    def title(self): ...
    @title.setter
    def title(self, title) -> None: ...
    @property
    def subtitle(self): ...
    @subtitle.setter
    def subtitle(self, subtitle) -> None: ...
    @property
    def original_title(self): ...
    @original_title.setter
    def original_title(self, original_title) -> None: ...
    @property
    def work_id(self): ...
    @work_id.setter
    def work_id(self, work_id) -> None: ...
    @property
    def container(self): ...
    @container.setter
    def container(self, container) -> None: ...
    @property
    def files(self): ...
    @files.setter
    def files(self, files) -> None: ...
    @property
    def filesets(self): ...
    @filesets.setter
    def filesets(self, filesets) -> None: ...
    @property
    def webcaptures(self): ...
    @webcaptures.setter
    def webcaptures(self, webcaptures) -> None: ...
    @property
    def container_id(self): ...
    @container_id.setter
    def container_id(self, container_id) -> None: ...
    @property
    def release_type(self): ...
    @release_type.setter
    def release_type(self, release_type) -> None: ...
    @property
    def release_stage(self): ...
    @release_stage.setter
    def release_stage(self, release_stage) -> None: ...
    @property
    def release_date(self): ...
    @release_date.setter
    def release_date(self, release_date) -> None: ...
    @property
    def release_year(self): ...
    @release_year.setter
    def release_year(self, release_year) -> None: ...
    @property
    def withdrawn_status(self): ...
    @withdrawn_status.setter
    def withdrawn_status(self, withdrawn_status) -> None: ...
    @property
    def withdrawn_date(self): ...
    @withdrawn_date.setter
    def withdrawn_date(self, withdrawn_date) -> None: ...
    @property
    def withdrawn_year(self): ...
    @withdrawn_year.setter
    def withdrawn_year(self, withdrawn_year) -> None: ...
    @property
    def ext_ids(self): ...
    @ext_ids.setter
    def ext_ids(self, ext_ids) -> None: ...
    @property
    def volume(self): ...
    @volume.setter
    def volume(self, volume) -> None: ...
    @property
    def issue(self): ...
    @issue.setter
    def issue(self, issue) -> None: ...
    @property
    def pages(self): ...
    @pages.setter
    def pages(self, pages) -> None: ...
    @property
    def number(self): ...
    @number.setter
    def number(self, number) -> None: ...
    @property
    def version(self): ...
    @version.setter
    def version(self, version) -> None: ...
    @property
    def publisher(self): ...
    @publisher.setter
    def publisher(self, publisher) -> None: ...
    @property
    def language(self): ...
    @language.setter
    def language(self, language) -> None: ...
    @property
    def license_slug(self): ...
    @license_slug.setter
    def license_slug(self, license_slug) -> None: ...
    @property
    def contribs(self): ...
    @contribs.setter
    def contribs(self, contribs) -> None: ...
    @property
    def refs(self): ...
    @refs.setter
    def refs(self, refs) -> None: ...
    @property
    def abstracts(self): ...
    @abstracts.setter
    def abstracts(self, abstracts) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
