from typing import Any

class ReleaseContrib:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, index: Any | None = ..., creator_id: Any | None = ..., creator: Any | None = ..., raw_name: Any | None = ..., given_name: Any | None = ..., surname: Any | None = ..., role: Any | None = ..., raw_affiliation: Any | None = ..., extra: Any | None = ...) -> None: ...
    @property
    def index(self): ...
    @index.setter
    def index(self, index) -> None: ...
    @property
    def creator_id(self): ...
    @creator_id.setter
    def creator_id(self, creator_id) -> None: ...
    @property
    def creator(self): ...
    @creator.setter
    def creator(self, creator) -> None: ...
    @property
    def raw_name(self): ...
    @raw_name.setter
    def raw_name(self, raw_name) -> None: ...
    @property
    def given_name(self): ...
    @given_name.setter
    def given_name(self, given_name) -> None: ...
    @property
    def surname(self): ...
    @surname.setter
    def surname(self, surname) -> None: ...
    @property
    def role(self): ...
    @role.setter
    def role(self, role) -> None: ...
    @property
    def raw_affiliation(self): ...
    @raw_affiliation.setter
    def raw_affiliation(self, raw_affiliation) -> None: ...
    @property
    def extra(self): ...
    @extra.setter
    def extra(self, extra) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
