from typing import Any

class WebcaptureCdxLine:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, surt: Any | None = ..., timestamp: Any | None = ..., url: Any | None = ..., mimetype: Any | None = ..., status_code: Any | None = ..., size: Any | None = ..., sha1: Any | None = ..., sha256: Any | None = ...) -> None: ...
    @property
    def surt(self): ...
    @surt.setter
    def surt(self, surt) -> None: ...
    @property
    def timestamp(self): ...
    @timestamp.setter
    def timestamp(self, timestamp) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url) -> None: ...
    @property
    def mimetype(self): ...
    @mimetype.setter
    def mimetype(self, mimetype) -> None: ...
    @property
    def status_code(self): ...
    @status_code.setter
    def status_code(self, status_code) -> None: ...
    @property
    def size(self): ...
    @size.setter
    def size(self, size) -> None: ...
    @property
    def sha1(self): ...
    @sha1.setter
    def sha1(self, sha1) -> None: ...
    @property
    def sha256(self): ...
    @sha256.setter
    def sha256(self, sha256) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
