from typing import Any, Optional, Dict, List
from fatcat_openapi_client import ReleaseEntity

class WebcaptureEntity:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, state: Optional[str] = ..., ident: Optional[str] = ..., revision: Optional[str] = ..., redirect: Optional[str] = ..., extra: Optional[Dict[str, Any]] = ..., edit_extra: Optional[Dict[str, Any]] = ..., cdx: Any | None = ..., archive_urls: Any | None = ..., original_url: Any | None = ..., timestamp: Any | None = ..., content_scope: Optional[str] = ..., release_ids: Optional[List[str]] = ..., releases: Optional[List[ReleaseEntity]] = ...) -> None: ...
    @property
    def state(self) -> Optional[str]: ...
    @state.setter
    def state(self, state: Optional[str]) -> None: ...
    @property
    def ident(self) -> Optional[str]: ...
    @ident.setter
    def ident(self, ident: Optional[str]) -> None: ...
    @property
    def revision(self) -> Optional[str]: ...
    @revision.setter
    def revision(self, revision: Optional[str]) -> None: ...
    @property
    def redirect(self) -> Optional[str]: ...
    @redirect.setter
    def redirect(self, redirect: Optional[str]) -> None: ...
    @property
    def extra(self) -> Optional[Dict[str, Any]]: ...
    @extra.setter
    def extra(self, extra: Optional[Dict[str, Any]]) -> None: ...
    @property
    def edit_extra(self) -> Optional[Dict[str, Any]]: ...
    @edit_extra.setter
    def edit_extra(self, edit_extra: Optional[Dict[str, Any]]) -> None: ...
    @property
    def cdx(self): ...
    @cdx.setter
    def cdx(self, cdx) -> None: ...
    @property
    def archive_urls(self): ...
    @archive_urls.setter
    def archive_urls(self, archive_urls) -> None: ...
    @property
    def original_url(self): ...
    @original_url.setter
    def original_url(self, original_url) -> None: ...
    @property
    def timestamp(self): ...
    @timestamp.setter
    def timestamp(self, timestamp) -> None: ...
    @property
    def content_scope(self) -> Optional[str]: ...
    @content_scope.setter
    def content_scope(self, content_scope: Optional[str]) -> None: ...
    @property
    def release_ids(self) -> Optional[List[ReleaseEntity]]: ...
    @release_ids.setter
    def release_ids(self, release_ids: Optional[List[ReleaseEntity]]) -> None: ...
    @property
    def releases(self) -> Optional[List[ReleaseEntity]]: ...
    @releases.setter
    def releases(self, releases: Optional[List[ReleaseEntity]]) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
