from typing import Any

class WebcaptureEntity:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, state: Any | None = ..., ident: Any | None = ..., revision: Any | None = ..., redirect: Any | None = ..., extra: Any | None = ..., edit_extra: Any | None = ..., cdx: Any | None = ..., archive_urls: Any | None = ..., original_url: Any | None = ..., timestamp: Any | None = ..., content_scope: Any | None = ..., release_ids: Any | None = ..., releases: Any | None = ...) -> None: ...
    @property
    def state(self): ...
    @state.setter
    def state(self, state) -> None: ...
    @property
    def ident(self): ...
    @ident.setter
    def ident(self, ident) -> None: ...
    @property
    def revision(self): ...
    @revision.setter
    def revision(self, revision) -> None: ...
    @property
    def redirect(self): ...
    @redirect.setter
    def redirect(self, redirect) -> None: ...
    @property
    def extra(self): ...
    @extra.setter
    def extra(self, extra) -> None: ...
    @property
    def edit_extra(self): ...
    @edit_extra.setter
    def edit_extra(self, edit_extra) -> None: ...
    @property
    def cdx(self): ...
    @cdx.setter
    def cdx(self, cdx) -> None: ...
    @property
    def archive_urls(self): ...
    @archive_urls.setter
    def archive_urls(self, archive_urls) -> None: ...
    @property
    def original_url(self): ...
    @original_url.setter
    def original_url(self, original_url) -> None: ...
    @property
    def timestamp(self): ...
    @timestamp.setter
    def timestamp(self, timestamp) -> None: ...
    @property
    def content_scope(self): ...
    @content_scope.setter
    def content_scope(self, content_scope) -> None: ...
    @property
    def release_ids(self): ...
    @release_ids.setter
    def release_ids(self, release_ids) -> None: ...
    @property
    def releases(self): ...
    @releases.setter
    def releases(self, releases) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
