from typing import Any

class WebcaptureUrl:
    openapi_types: Any
    attribute_map: Any
    discriminator: Any
    def __init__(self, url: Any | None = ..., rel: Any | None = ...) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url) -> None: ...
    @property
    def rel(self): ...
    @rel.setter
    def rel(self, rel) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
