# coding: utf-8

"""
    fatcat

    A scalable, versioned, API-oriented catalog of bibliographic entities and file metadata  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ReleaseEntityAbstracts(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sha1': 'str',
        'content': 'str',
        'mimetype': 'str',
        'lang': 'str'
    }

    attribute_map = {
        'sha1': 'sha1',
        'content': 'content',
        'mimetype': 'mimetype',
        'lang': 'lang'
    }

    def __init__(self, sha1=None, content=None, mimetype=None, lang=None):  # noqa: E501
        """ReleaseEntityAbstracts - a model defined in Swagger"""  # noqa: E501

        self._sha1 = None
        self._content = None
        self._mimetype = None
        self._lang = None
        self.discriminator = None

        if sha1 is not None:
            self.sha1 = sha1
        if content is not None:
            self.content = content
        if mimetype is not None:
            self.mimetype = mimetype
        if lang is not None:
            self.lang = lang

    @property
    def sha1(self):
        """Gets the sha1 of this ReleaseEntityAbstracts.  # noqa: E501


        :return: The sha1 of this ReleaseEntityAbstracts.  # noqa: E501
        :rtype: str
        """
        return self._sha1

    @sha1.setter
    def sha1(self, sha1):
        """Sets the sha1 of this ReleaseEntityAbstracts.


        :param sha1: The sha1 of this ReleaseEntityAbstracts.  # noqa: E501
        :type: str
        """

        self._sha1 = sha1

    @property
    def content(self):
        """Gets the content of this ReleaseEntityAbstracts.  # noqa: E501


        :return: The content of this ReleaseEntityAbstracts.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this ReleaseEntityAbstracts.


        :param content: The content of this ReleaseEntityAbstracts.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def mimetype(self):
        """Gets the mimetype of this ReleaseEntityAbstracts.  # noqa: E501


        :return: The mimetype of this ReleaseEntityAbstracts.  # noqa: E501
        :rtype: str
        """
        return self._mimetype

    @mimetype.setter
    def mimetype(self, mimetype):
        """Sets the mimetype of this ReleaseEntityAbstracts.


        :param mimetype: The mimetype of this ReleaseEntityAbstracts.  # noqa: E501
        :type: str
        """

        self._mimetype = mimetype

    @property
    def lang(self):
        """Gets the lang of this ReleaseEntityAbstracts.  # noqa: E501


        :return: The lang of this ReleaseEntityAbstracts.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this ReleaseEntityAbstracts.


        :param lang: The lang of this ReleaseEntityAbstracts.  # noqa: E501
        :type: str
        """

        self._lang = lang

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReleaseEntityAbstracts):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
