# coding: utf-8

"""
    fatcat

    A scalable, versioned, API-oriented catalog of bibliographic entities and file metadata  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class WorkEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'work_type': 'str',
        'extra': 'object',
        'editgroup_id': 'str',
        'redirect': 'str',
        'revision': 'str',
        'ident': 'str',
        'state': 'str'
    }

    attribute_map = {
        'work_type': 'work_type',
        'extra': 'extra',
        'editgroup_id': 'editgroup_id',
        'redirect': 'redirect',
        'revision': 'revision',
        'ident': 'ident',
        'state': 'state'
    }

    def __init__(self, work_type=None, extra=None, editgroup_id=None, redirect=None, revision=None, ident=None, state=None):  # noqa: E501
        """WorkEntity - a model defined in Swagger"""  # noqa: E501

        self._work_type = None
        self._extra = None
        self._editgroup_id = None
        self._redirect = None
        self._revision = None
        self._ident = None
        self._state = None
        self.discriminator = None

        if work_type is not None:
            self.work_type = work_type
        if extra is not None:
            self.extra = extra
        if editgroup_id is not None:
            self.editgroup_id = editgroup_id
        if redirect is not None:
            self.redirect = redirect
        if revision is not None:
            self.revision = revision
        if ident is not None:
            self.ident = ident
        if state is not None:
            self.state = state

    @property
    def work_type(self):
        """Gets the work_type of this WorkEntity.  # noqa: E501


        :return: The work_type of this WorkEntity.  # noqa: E501
        :rtype: str
        """
        return self._work_type

    @work_type.setter
    def work_type(self, work_type):
        """Sets the work_type of this WorkEntity.


        :param work_type: The work_type of this WorkEntity.  # noqa: E501
        :type: str
        """

        self._work_type = work_type

    @property
    def extra(self):
        """Gets the extra of this WorkEntity.  # noqa: E501


        :return: The extra of this WorkEntity.  # noqa: E501
        :rtype: object
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """Sets the extra of this WorkEntity.


        :param extra: The extra of this WorkEntity.  # noqa: E501
        :type: object
        """

        self._extra = extra

    @property
    def editgroup_id(self):
        """Gets the editgroup_id of this WorkEntity.  # noqa: E501


        :return: The editgroup_id of this WorkEntity.  # noqa: E501
        :rtype: str
        """
        return self._editgroup_id

    @editgroup_id.setter
    def editgroup_id(self, editgroup_id):
        """Sets the editgroup_id of this WorkEntity.


        :param editgroup_id: The editgroup_id of this WorkEntity.  # noqa: E501
        :type: str
        """

        self._editgroup_id = editgroup_id

    @property
    def redirect(self):
        """Gets the redirect of this WorkEntity.  # noqa: E501


        :return: The redirect of this WorkEntity.  # noqa: E501
        :rtype: str
        """
        return self._redirect

    @redirect.setter
    def redirect(self, redirect):
        """Sets the redirect of this WorkEntity.


        :param redirect: The redirect of this WorkEntity.  # noqa: E501
        :type: str
        """

        self._redirect = redirect

    @property
    def revision(self):
        """Gets the revision of this WorkEntity.  # noqa: E501


        :return: The revision of this WorkEntity.  # noqa: E501
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """Sets the revision of this WorkEntity.


        :param revision: The revision of this WorkEntity.  # noqa: E501
        :type: str
        """

        self._revision = revision

    @property
    def ident(self):
        """Gets the ident of this WorkEntity.  # noqa: E501


        :return: The ident of this WorkEntity.  # noqa: E501
        :rtype: str
        """
        return self._ident

    @ident.setter
    def ident(self, ident):
        """Sets the ident of this WorkEntity.


        :param ident: The ident of this WorkEntity.  # noqa: E501
        :type: str
        """

        self._ident = ident

    @property
    def state(self):
        """Gets the state of this WorkEntity.  # noqa: E501


        :return: The state of this WorkEntity.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this WorkEntity.


        :param state: The state of this WorkEntity.  # noqa: E501
        :type: str
        """
        allowed_values = ["wip", "active", "redirect", "deleted"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
