# coding: utf-8

"""
    fatcat

    A scalable, versioned, API-oriented catalog of bibliographic entities and file metadata  # noqa: E501

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fatcat_client
from fatcat_client.models.fileset_url import FilesetUrl  # noqa: E501
from fatcat_client.rest import ApiException


class TestFilesetUrl(unittest.TestCase):
    """FilesetUrl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilesetUrl(self):
        """Test FilesetUrl"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fatcat_client.models.fileset_url.FilesetUrl()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
