# coding: utf-8

"""
    fatcat

    A scalable, versioned, API-oriented catalog of bibliographic entities and file metadata  # noqa: E501

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fatcat_client
from fatcat_client.models.webcapture_url import WebcaptureUrl  # noqa: E501
from fatcat_client.rest import ApiException


class TestWebcaptureUrl(unittest.TestCase):
    """WebcaptureUrl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebcaptureUrl(self):
        """Test WebcaptureUrl"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fatcat_client.models.webcapture_url.WebcaptureUrl()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
