# coding: utf-8

"""
    fatcat

    A scalable, versioned, API-oriented catalog of bibliographic entities and file metadata  # noqa: E501

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fatcat_openapi_client
from fatcat_openapi_client.models.fileset_file import FilesetFile  # noqa: E501
from fatcat_openapi_client.rest import ApiException


class TestFilesetFile(unittest.TestCase):
    """FilesetFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilesetFile(self):
        """Test FilesetFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fatcat_openapi_client.models.fileset_file.FilesetFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
