"""
    fatcat

    Fatcat is a scalable, versioned, API-oriented catalog of bibliographic entities and file metadata.   # noqa: E501

    The version of the OpenAPI document: 0.5.0
    Contact: webservices@archive.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import fatcat_openapi_client
from fatcat_openapi_client.api.filesets_api import FilesetsApi  # noqa: E501


class TestFilesetsApi(unittest.TestCase):
    """FilesetsApi unit test stubs"""

    def setUp(self):
        self.api = FilesetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_fileset(self):
        """Test case for create_fileset

        """
        pass

    def test_create_fileset_auto_batch(self):
        """Test case for create_fileset_auto_batch

        """
        pass

    def test_delete_fileset(self):
        """Test case for delete_fileset

        """
        pass

    def test_delete_fileset_edit(self):
        """Test case for delete_fileset_edit

        """
        pass

    def test_get_fileset(self):
        """Test case for get_fileset

        """
        pass

    def test_get_fileset_edit(self):
        """Test case for get_fileset_edit

        """
        pass

    def test_get_fileset_history(self):
        """Test case for get_fileset_history

        """
        pass

    def test_get_fileset_redirects(self):
        """Test case for get_fileset_redirects

        """
        pass

    def test_get_fileset_revision(self):
        """Test case for get_fileset_revision

        """
        pass

    def test_update_fileset(self):
        """Test case for update_fileset

        """
        pass


if __name__ == '__main__':
    unittest.main()
