# coding: utf-8

"""
    fatcat

    Fatcat is a scalable, versioned, API-oriented catalog of bibliographic entities and file metadata.   # noqa: E501

    OpenAPI spec version: 0.3.0
    Contact: webservices@archive.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fatcat_openapi_client
from fatcat_openapi_client.models.creator_auto_batch import CreatorAutoBatch  # noqa: E501
from fatcat_openapi_client.rest import ApiException


class TestCreatorAutoBatch(unittest.TestCase):
    """CreatorAutoBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatorAutoBatch(self):
        """Test CreatorAutoBatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fatcat_openapi_client.models.creator_auto_batch.CreatorAutoBatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
