"""
    fatcat

    Fatcat is a scalable, versioned, API-oriented catalog of bibliographic entities and file metadata.   # noqa: E501

    The version of the OpenAPI document: 0.5.0
    Contact: webservices@archive.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import fatcat_openapi_client
from fatcat_openapi_client.api.releases_api import ReleasesApi  # noqa: E501


class TestReleasesApi(unittest.TestCase):
    """ReleasesApi unit test stubs"""

    def setUp(self):
        self.api = ReleasesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_release(self):
        """Test case for create_release

        """
        pass

    def test_create_release_auto_batch(self):
        """Test case for create_release_auto_batch

        """
        pass

    def test_delete_release(self):
        """Test case for delete_release

        """
        pass

    def test_delete_release_edit(self):
        """Test case for delete_release_edit

        """
        pass

    def test_get_release(self):
        """Test case for get_release

        """
        pass

    def test_get_release_edit(self):
        """Test case for get_release_edit

        """
        pass

    def test_get_release_files(self):
        """Test case for get_release_files

        """
        pass

    def test_get_release_filesets(self):
        """Test case for get_release_filesets

        """
        pass

    def test_get_release_history(self):
        """Test case for get_release_history

        """
        pass

    def test_get_release_redirects(self):
        """Test case for get_release_redirects

        """
        pass

    def test_get_release_revision(self):
        """Test case for get_release_revision

        """
        pass

    def test_get_release_webcaptures(self):
        """Test case for get_release_webcaptures

        """
        pass

    def test_lookup_release(self):
        """Test case for lookup_release

        """
        pass

    def test_update_release(self):
        """Test case for update_release

        """
        pass


if __name__ == '__main__':
    unittest.main()
