"""
    fatcat

    Fatcat is a scalable, versioned, API-oriented catalog of bibliographic entities and file metadata.   # noqa: E501

    The version of the OpenAPI document: 0.5.0
    Contact: webservices@archive.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import fatcat_openapi_client
from fatcat_openapi_client.api.files_api import FilesApi  # noqa: E501


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self):
        self.api = FilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_file(self):
        """Test case for create_file

        """
        pass

    def test_create_file_auto_batch(self):
        """Test case for create_file_auto_batch

        """
        pass

    def test_delete_file(self):
        """Test case for delete_file

        """
        pass

    def test_delete_file_edit(self):
        """Test case for delete_file_edit

        """
        pass

    def test_get_file(self):
        """Test case for get_file

        """
        pass

    def test_get_file_edit(self):
        """Test case for get_file_edit

        """
        pass

    def test_get_file_history(self):
        """Test case for get_file_history

        """
        pass

    def test_get_file_redirects(self):
        """Test case for get_file_redirects

        """
        pass

    def test_get_file_revision(self):
        """Test case for get_file_revision

        """
        pass

    def test_lookup_file(self):
        """Test case for lookup_file

        """
        pass

    def test_update_file(self):
        """Test case for update_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
