"""
    fatcat

    Fatcat is a scalable, versioned, API-oriented catalog of bibliographic entities and file metadata.   # noqa: E501

    The version of the OpenAPI document: 0.5.0
    Contact: webservices@archive.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import fatcat_openapi_client
from fatcat_openapi_client.api.creators_api import CreatorsApi  # noqa: E501


class TestCreatorsApi(unittest.TestCase):
    """CreatorsApi unit test stubs"""

    def setUp(self):
        self.api = CreatorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_creator(self):
        """Test case for create_creator

        """
        pass

    def test_create_creator_auto_batch(self):
        """Test case for create_creator_auto_batch

        """
        pass

    def test_delete_creator(self):
        """Test case for delete_creator

        """
        pass

    def test_delete_creator_edit(self):
        """Test case for delete_creator_edit

        """
        pass

    def test_get_creator(self):
        """Test case for get_creator

        """
        pass

    def test_get_creator_edit(self):
        """Test case for get_creator_edit

        """
        pass

    def test_get_creator_history(self):
        """Test case for get_creator_history

        """
        pass

    def test_get_creator_redirects(self):
        """Test case for get_creator_redirects

        """
        pass

    def test_get_creator_releases(self):
        """Test case for get_creator_releases

        """
        pass

    def test_get_creator_revision(self):
        """Test case for get_creator_revision

        """
        pass

    def test_lookup_creator(self):
        """Test case for lookup_creator

        """
        pass

    def test_update_creator(self):
        """Test case for update_creator

        """
        pass


if __name__ == '__main__':
    unittest.main()
