"""
    fatcat

    Fatcat is a scalable, versioned, API-oriented catalog of bibliographic entities and file metadata.   # noqa: E501

    The version of the OpenAPI document: 0.3.1
    Contact: webservices@archive.org
    Generated by: https://openapi-generator.tech
"""



import unittest

import fatcat_openapi_client
from fatcat_openapi_client.models.success import Success  # noqa: E501
from fatcat_openapi_client.rest import ApiException


class TestSuccess(unittest.TestCase):
    """Success unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuccess(self):
        """Test Success"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fatcat_openapi_client.models.success.Success()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
