"""
    fatcat

    Fatcat is a scalable, versioned, API-oriented catalog of bibliographic entities and file metadata.   # noqa: E501

    The version of the OpenAPI document: 0.3.1
    Contact: webservices@archive.org
    Generated by: https://openapi-generator.tech
"""



import unittest

import fatcat_openapi_client
from fatcat_openapi_client.models.work_auto_batch import WorkAutoBatch  # noqa: E501
from fatcat_openapi_client.rest import ApiException


class TestWorkAutoBatch(unittest.TestCase):
    """WorkAutoBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkAutoBatch(self):
        """Test WorkAutoBatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fatcat_openapi_client.models.work_auto_batch.WorkAutoBatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
