"""
    fatcat

    Fatcat is a scalable, versioned, API-oriented catalog of bibliographic entities and file metadata.   # noqa: E501

    The version of the OpenAPI document: 0.5.0
    Contact: webservices@archive.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fatcat_openapi_client
from fatcat_openapi_client.model.entity_edit import EntityEdit
globals()['EntityEdit'] = EntityEdit
from fatcat_openapi_client.model.editgroup_edits import EditgroupEdits


class TestEditgroupEdits(unittest.TestCase):
    """EditgroupEdits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditgroupEdits(self):
        """Test EditgroupEdits"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EditgroupEdits()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
