# coding: utf-8

"""
    fatcat

    Fatcat is a scalable, versioned, API-oriented catalog of bibliographic entities and file metadata.   # noqa: E501

    OpenAPI spec version: 0.3.0
    Contact: webservices@archive.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fatcat_openapi_client
from fatcat_openapi_client.models.webcapture_cdx_line import WebcaptureCdxLine  # noqa: E501
from fatcat_openapi_client.rest import ApiException


class TestWebcaptureCdxLine(unittest.TestCase):
    """WebcaptureCdxLine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebcaptureCdxLine(self):
        """Test WebcaptureCdxLine"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fatcat_openapi_client.models.webcapture_cdx_line.WebcaptureCdxLine()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
