"""
    fatcat

    Fatcat is a scalable, versioned, API-oriented catalog of bibliographic entities and file metadata.   # noqa: E501

    The version of the OpenAPI document: 0.5.0
    Contact: webservices@archive.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fatcat_openapi_client
from fatcat_openapi_client.model.release_entity import ReleaseEntity
from fatcat_openapi_client.model.webcapture_cdx_line import WebcaptureCdxLine
from fatcat_openapi_client.model.webcapture_url import WebcaptureUrl
globals()['ReleaseEntity'] = ReleaseEntity
globals()['WebcaptureCdxLine'] = WebcaptureCdxLine
globals()['WebcaptureUrl'] = WebcaptureUrl
from fatcat_openapi_client.model.webcapture_entity import WebcaptureEntity


class TestWebcaptureEntity(unittest.TestCase):
    """WebcaptureEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebcaptureEntity(self):
        """Test WebcaptureEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WebcaptureEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
